==== Ansible Tower Config

laptop]# scp -i /home/<username>/.ssh/your-key.pem /home/<username>/.ssh/your-key.pem username  company.name@bastion.<GUID>.example.com:/tmp

laptop]# ssh -i /home/<username>/.ssh/your-key.pem  username-company.name@bastion.<GUID>.example.com

bastion]$  sudo -i

bastion]# cp /tmp/<your-key.pem>  /root/.ssh/mykey.pem

bastion]# chmod 0400 /root/.ssh/mykey.pem;chown root:root /root/.ssh/mykey.pem

bastion]# git clone https://github.com/Lokesh331/ansible_advance_homework.git

bastion]# cd ansible_advance_homework

Update the variables as per your Lab environment


bastion]#cat towerconfig-variables

        TOWER_GUID=<bastion env GUID>
        OSP_GUID=<openstack env GUID>
        PRIVATE_KEY=~/.ssh/mykey.pem
        OPENTLC_LOGIN=<opentlc-username>
        OPENTLC_PASSWORD=<password>
        GITHUB_REPO=https://github.com/Lokesh331/ansible_advance_homework.git
        JQ_REPO_BASE=http://www.opentlc.com/download/ansible_bootcamp
        REGION=us-east-1
        RH_MAIL_ID=<username@company.name>

        GLOBAL_VARS="
        OSP_GUID=${OSP_GUID}
        GUID=${TOWER_GUID}
        ansible_user=${OPENTLC_LOGIN}
        ansible_ssh_private_key_file=${PRIVATE_KEY}
        opentlc_login=${OPENTLC_LOGIN}
        opentlc_password=${OPENTLC_PASSWORD}
        param_repo_base=${GITHUB_REPO}
        tower_GUID=${TOWER_GUID}
        path_to_opentlc_key=${PRIVATE_KEY}
        github_repo=${GITHUB_REPO}
        osp_GUID=${OSP_GUID}
        REGION_NAME=${REGION}
        EMAIL=${RH_MAIL_ID}
        “
        
bastion]# source towerconfig-variables


bastion]# ansible-playbook   main.yml -e "${GLOBAL_VARS}"

- import_playbook: site-setup-workstation.yml
- import_playbook: site-config-tower.yml 

Execute CI/CD work flow:
----------------------------------

login to one of the Ansible tower and execute cicd_workflow work flow

https://tower(1-3).{{TOWER_GUID}}.example.opentlc.com

Username:admin
Password:<default ansible tower password>

Go to templates and select cicd_workflow and click on rocket symbol


For Validating grade
----------------------------

OSP_GUID=<openstack env GUID>

ANSIBLE_ADVANCE_GUID=<Three tier App aws env GUID>

ansible-playbook grading-script.yml -e OSP_GUID=${OSP_GUID} -e ANSIBLE_ADVANCE_GUID=${ANSIBLE_ADVANCE_GUID} 


----


.List of Playbooks
[%header,cols=2*]
|===
| Files or dir | Purpose
| main.yml | main playbook to call site-setup-workstation.yml and site-osp-instances.yml playbooks
| app-tier | Install application server role
| db-tier  | Install postgressql server for database role
| lb-tier  | Install HA proxy role
| base-config | Setup yum repo and base packages role
| setup-workstation | Setup workstation, create network, ssh keypair, security group etc. role 
| osp-servers | Provision OSP Instances role
| osp-instance-delete | Delete OSP Instances role
| osp-facts | Genrate in-memory inventory for OSP instances role
| roles/config-tower/vars/main.yml | Very important file to review. All the variable values are set there. Please do not make any changes in the file
| config-tower | Role to configure ansible tower job templates and workflow
| aws_creds.yml | Fetch GUIDkey.pem from bastion of Three tier application env and create machine credential to connect to AWS instances
| aws_provision.yml | Use `order_svc.sh` script to provision env
| aws_status_check.yml | Check aws instances are up or not
| site-3tier-app.yml | Playbook to deploy three tier app
| site-install-isolated-node.yml | Playbook to install isolated node
| site-config-tower.yml | Playbook to call role `config-tower`
| site-osp-delete.yml | Playbook to call role
| site-osp-instances.yml | Playbook to call role
| site-setup-workstation.yml | Playbook to call role
| site-smoke-osp.yml | Playbook to test three tier app on OSP
| site-smoketest-aws.yml | Playbook to test three tier app on AWS
| grading-script.yml | Self grading script
| roles/config-tower/tasks/ec2_dynamic.yml | For creating Dynamic inventory in Ansible tower. Use `AWS Access Key` for credential
| roles/config-tower/tasks/job_template.yml | For creating job templates
| roles/config-tower/tasks/pre-config-tower.yml | Any pre config tasks needed
| roles/config-tower/tasks/workflow_template.yml | genrate workflow from `workflow.yml` file
| roles/config-tower/tasks/post-config-tower.yml | any post config jobs
|===
